# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d7affdcb0661cdd17bc951ea9189b1a6e806f813fccab4ebae33071a3a8f5390fe246c2f18cabda8db14c41e7170248441a027e733bcbff673f5b92802fd1e

test:
  secret_key_base: 7f722296e340a4a308a991b009d0d8f9336b67c9302abf8c0f9976b889cb49a8788e42acb90be3352ddfa7ce1f72ef499d41648d18a90827498a65f5df98b347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
