# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56a11d0a69ec626791c96ee03343fdd392bedf329043559edeabae0174e6f2e2338529b6a47f3f5167ccd3870c922c8d83692eb4d5d6885cd3b7c51293f7d142

test:
  secret_key_base: 9e84493d9efd514d752ec252552d16bebae63a7bddc19e73aed6b1778d26890ef1163b6795ce6f260d0367f27d7ae2ee2a6a4c43011b21803bd2d6a776efdc36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
